print('Speed Calculator:')
run = float(input('Length of Run in KM ?'))
hr = int(input('Hour of Run ?'))
minutes = int(input('Minutes of Run ?'))
sec = int(input('Seconds of Run ?'))
time = float(hr*60 + minutes + sec/60)
speed = (run/1.61)/(time/60)
print('\nTime Used = %0.2f' %time) #Need Fix Here: & '\n HRs')
print('\nSpeed MPH = %0.2f' %speed)
